export const financialTerms: string[] = [
  "50/30/20 Kuralı",
  "A Tipi Yatırım Fonu",
  "ABD MerkezBankası Fed",
  "ABİGEM (Avrupa Birliği Türkiye İş Geliştirme Merkezleri)",
  "ARDEB",
  "Acente",
  "Adat",
  "Adi Hisse Senedi",
  "AkademiO",
  "Akreditasyon",
  "Akreditif",
  "Aktif",
  "Akıl Yürütme Yöntemi",
  "Akım Değişken",
  "Algoritma",
  "Alt Yüklenici",
  "Alternatif Maliyet",
  "Altın",
  "Altın Rezervi",
  "Altın Standardı",
  "Alım Heyeti",
  "Alım Satım",
  "Alım Satım Opsiyonu",
  "Alış (Bid) Fiyatı",
  "Alış Fiyatı",
  "Alış Satış Farkı",
  "Alış Satış Sinyali",
  "Alış kuru",
  "Amerikan Opsiyonu",
  "Amortisman",
  "Anapara",
  "Ankes",
  "Anüite",
  "Ar-Ge",
  "Ar-Ge (Araştırma ve Geliştirme)",
  "Aracı Kurum",
  "Arazi Kullanım Kabiliyet Sınıfı (AKKS)",
  "Arazi Tevhidi",
  "Arbitraj",
  "Artan Trend Kanalı",
  "Artırımlı Bütçe",
  "Arz Yönlü Ekonomi Supply Side Economics",
  "Asgari Ücret",
  "Asimetrik Bilgi",
  "Asit-Test (Likidite) Oranı",
  "Atık Bertaraf",
  "Avan Proje",
  "Avrupa Birliği European Union",
  "Avrupa Yatırım Bankası",
  "Avrupa İstikrar Mekanizması",
  "Aylık Bütçe",
  "Ayni Katkı",
  "Ayrışma Decoupling",
  "Ayı Piyasası",
  "Açık Bütçe",
  "Açık Kredi",
  "Açık Pazar",
  "Açık Piyasa İşlemleri",
  "Açık Piyasa İşlemleri (APİ)",
  "Açık Pozisyon",
  "Açık Pozisyon Short Position",
  "Açık Poziyon",
  "Açık iç ve dış ekonomik denge açıkları",
  "Açık piyasa işlemleri APİ",
  "Açığa Satış",
  "Açığa Satış İşlemleri",
  "B2B",
  "B2B / B2C / B2G",
  "B2C",
  "B2G",
  "BES",
  "BES (Bireysel Emeklilik Sistemi)",
  "BIST",
  "BIST  Banka Endeksi",
  "BIST  Endeksi",
  "BIST Endeksi",
  "BIST Endeksleri BIST  Endeksi",
  "BIST100 Endeksi",
  "BOE",
  "BOE (Bank of England)",
  "BOJ",
  "BOJ (Bank of Japan)",
  "Balon ya da Köpük ekonomik anlamı",
  "Bankacılık",
  "Basel Komitesi",
  "Basit Faiz",
  "Batık Kredi",
  "Baz Döviz",
  "Baz Etkisi",
  "Bağlantı Anlaşmasına Çağrı Mektubu",
  "Bağlantı ve Sistem Kullanma Anlaşması",
  "Başabaş Analizi",
  "Başabaş Noktası",
  "Başlangıç Marjı",
  "Başlangıç Marjı (Teminatı)",
  "Bedelsiz İhracat",
  "Beklentiler Expectation",
  "Benchmarking",
  "Benchmarking (Kıyaslama)",
  "Beta (β) Katsayısı",
  "Beta Katsayısı",
  "Bilanço",
  "Bileşik Faiz",
  "Birikim",
  "Bitcoin",
  "Biyokütle",
  "Blockchain",
  "Bono",
  "Borsa",
  "Borç",
  "Borç (Kaldıraç) Oranı",
  "Borç Sarmalı",
  "Borç Servisi",
  "Borç Stoku",
  "Borç Tavanı",
  "Borç Yönetimi",
  "Borç Yükü Debt Burden",
  "Borçlanma",
  "Boğa Piyasası",
  "Boğa Piyasası (Bullish Market)",
  "Brent Petrol",
  "Bretton Woods Sistemi",
  "Broker",
  "Brownfield Investment",
  "Bugünkü Değer",
  "Bulyonizm",
  "Bölge Kalkınma İdaresi",
  "Bölgesel Teşvik Uygulamaları",
  "Bütçe",
  "Bütçe Açığı",
  "Bütçe Dengesi Budget Balance",
  "Büyüme",
  "C2C",
  "CDS Credit Default Swap",
  "CE Belgesi",
  "CFD",
  "CFD(Contracts For Difference)",
  "CIF",
  "CIF (Cost, Insurance and Freight)",
  "CRM",
  "Cable",
  "Call Opsiyonu",
  "Cari Denge Cari Açık veya Cari Fazla",
  "Cari Hesap",
  "Cari Oran",
  "Carry Trade",
  "Case  Shiller Endeksi",
  "Cazibe Merkezi",
  "Cazibe Merkezi Programı",
  "Cazibe Merkezi Programı (CMP)",
  "Cazibe Merkezleri Destekleme Programı",
  "Ceteris Paribus",
  "Ciro",
  "Coğrafi İşaret",
  "Cumhurbaşkanlığı Yatırım Ofisi",
  "DASK",
  "Dalgalı Kur",
  "Damping",
  "Davranışsal Ekonomi",
  "Dayanıklı Mal Siparişleri",
  "Deflasyon",
  "Demo İşlem Platformu",
  "Denk Bütçe",
  "Depo",
  "Depresyon",
  "Deregülasyon",
  "Destek Seviyesi",
  "Devalüasyon",
  "Devlet Tahvili",
  "Dezenflasyon",
  "Değer Kazanma",
  "Değer Maksimizasyonu (Hissedar Refahı) Yaklaşımı",
  "Değer Çelişkisi",
  "Değişken",
  "Değişken Gider",
  "Dikey Analiz (Yüzde Yöntemi)",
  "Direnç seviyesi",
  "Disponibilite",
  "Diversifikasyon",
  "Dolar Endeksi",
  "Dolarizasyon",
  "Doğal işsizlik oranı",
  "Doğrudan Alım",
  "Doğrudan Satım",
  "Doğrudan Sermaye Yatırımı",
  "Doğrudan Yabancı Yatırım",
  "Doğrudan finansman",
  "Due Diligence",
  "Due Diligence (Durum Tespiti)",
  "Duran Varlıklar",
  "Dâhilde İşleme Rejimi",
  "Dönen Varlıklar",
  "Dördüncü Sanayi Devrimi",
  "Döviz",
  "Döviz (Forex)",
  "Döviz Depo İşlemleri",
  "Döviz Kredisi",
  "Döviz Kuru",
  "Döviz Riski",
  "Dövize Endeksli Kredi",
  "Dünya Bankası The World Bank IBRD",
  "Düşük Teknolojili Yatırım",
  "DİBS Devlet İç Borçlanma Senetleri",
  "Dış Ticaret",
  "Dış Ticaret Hacmi",
  "Dışticaret Dengesi Trade Balance",
  "E-TUYS",
  "E-Ticaret",
  "E-İhracat",
  "ECB",
  "ECB (European Central Bank)",
  "Ekonometri",
  "Ekonomi",
  "Ekonomide Büyüme ve Fiyatlar İlişkisi",
  "Ekonomide Isınma",
  "Ekonomik Büyüme",
  "Ekonomik Safsata",
  "Ekonomik Takvim",
  "Ekonomik işlemler",
  "Ekosistem",
  "Emlak Vergisi Muafiyeti",
  "Emperyalizm",
  "Emsal Değer",
  "Emtia",
  "Emtia ve Emtia Piyasası",
  "Endeks",
  "Endüstri Bölgesi",
  "Endüstriyel Simbiyoz",
  "Enflasyon",
  "Enflasyon Riski",
  "Enflasyon Vergisi",
  "Entegre Hayvancılık Yatırımı",
  "Erteleme ve Yeniden Finansman",
  "Esenlik Yatırımı",
  "Esneklik Elasticity",
  "Etki",
  "Euro",
  "Euro Bölgesi Euro Zone",
  "Eximbank",
  "Eğilim",
  "Eş Finansman",
  "FTSE  Endeksi",
  "Faaliyet (Etkinlik) Oranları",
  "Faiz",
  "Faiz Dışı Denge Primary Budget Balance",
  "Faiz Nedir Nasıl Belirlenir",
  "Faiz Oranı",
  "Faiz Oranı Riski",
  "Faiz veya Kâr Payı Desteği",
  "Faizsiz Kredi Desteği",
  "Faktoring",
  "Fayda yarar",
  "Finans",
  "Finansal Bilgi",
  "Finansal Bulaşıcılık",
  "Finansal Davranış",
  "Finansal Kaldıraç",
  "Finansal Kiralama (Leasing)",
  "Finansal Okuryazarlık",
  "Finansal Piyasalar",
  "Finansal Planlama",
  "Finansal Tutum",
  "Finansal Varlık",
  "Finansal Yönetim",
  "Finansal Ürünler",
  "Finansman",
  "Finansman Yapısı Oranları",
  "FinteK",
  "Fiyat",
  "Fiyat teorisi",
  "Fizibilite",
  "Fizibilite Raporu",
  "Fon (Kaynak) Sağlama İşlevi",
  "Fon Yöneticisi",
  "Forex ve Forex Piyasası Nedir",
  "Forward İşlemi",
  "Future İşlemi",
  "FİNTEK (Finansal Teknoloji)",
  "GSYH gayrısafi yurtiçi hasıla",
  "Gayrimenkul",
  "Gayrimenkul Yatırım Ortaklığı",
  "Gayrimenkul Yatırımı",
  "Gayrı Sıhhi Müessese",
  "Gelecek Değer",
  "Gelir",
  "Gelir Tablosu",
  "Gelir ve Kullanımı Tüketim ve Tasarruf",
  "Gelişme ekonomik gelişme",
  "Genel Bütçe",
  "Getiri Eğrisi",
  "Gevşeme Quantitative Easing QE",
  "Geç Likidite Penceresi",
  "Geçici Bütçe",
  "Gider",
  "Girişim (Risk) Sermayesi",
  "Girişim Sermayesi (Venture Capital)",
  "Girişimci Enterpreneur",
  "Greenfield Investment",
  "Gölge Bankacılık Shadow Banking",
  "Gösterge Faiz",
  "Gösteriş Tüketimi",
  "Gümrük Vergisi Muafiyeti",
  "Haftalık Bütçe",
  "Halka Arz",
  "Hanehalkı",
  "Harcama",
  "Hazine Bonosu",
  "Hazine Garantisi",
  "Hazine Geri Ödeme Garantisi",
  "Hazine Karşı Garantisi",
  "Hazine Nakit Dengesi",
  "Hazine Tahvili",
  "Hazine Yatırım Garantisi",
  "Hazine Ülke Garantisi",
  "Hedge",
  "Hedge Fon",
  "Hedge etmek",
  "Herfindahl  Hirshman Endeski",
  "Heterodoks Ekonomik Yaklaşım",
  "Hibe Desteği",
  "Hisse Başına Kr",
  "Hisse Bölünmesi",
  "Hisse Senedi",
  "Hisse Seçim Analiz Türleri",
  "I İ",
  "IMF",
  "J Eğrisi",
  "Jeopolotik Risk",
  "KDV İstisnası",
  "Kaldıraç",
  "Kaldıraç Oranı",
  "Kaliforniya Sendromu",
  "Kalkınma",
  "Kalkınma Ajansı",
  "Kamu Kesimi Dış Borçlanması",
  "Kamu Kesimi İç Borçlanması",
  "Kapasite Kullanım Oranı",
  "Kapasite Raporu",
  "Kapital",
  "Kapitülasyon",
  "Kartel",
  "Kaya petrolü",
  "Kemer Sıkma Önlemleri",
  "Kira Sertifikası",
  "Kişisel Finansal Planlama",
  "Know-how",
  "Komple Yeni Yatırım",
  "Konjonktür",
  "Konjonktür Dalgaları Business Cycle",
  "Konversiyon",
  "Konvertibilite",
  "Koruma",
  "Kredi",
  "Kredi Kartı",
  "Kredi Notlarının Anlamı",
  "Kredi Riski",
  "Kredi Yönetimi",
  "Kripto Para",
  "Kripto Paralar",
  "Kriptopara",
  "Kur",
  "Kur Rejimi",
  "Kur Riski",
  "Kur Savaşları",
  "Kur Sepeti",
  "Kârlılık Oranları",
  "Küreselleşme",
  "Kırılgan Beşli",
  "Kısa Pozisyon",
  "Kıyı Bankacılığı",
  "Libor",
  "Likidite",
  "Likidite Oranları",
  "Likidite Riski",
  "Likidite tuzağı Liquidity Trap",
  "Lot",
  "Makro Ekonomi",
  "Mali Anestezi",
  "Mali Destek Programı",
  "Mali Konsolidasyon Fiscal Consolidation",
  "Mali Kural Fiscal Rule",
  "Mali Piyasa",
  "Mali Sürüklenme Fiscal Drag",
  "Mali İllüzyon Fiscal Illusion",
  "Maliye Politikası Fiscal Policy",
  "Maliyet Ortalaması",
  "Manipülasyon",
  "Manşet Enflasyon",
  "Marjinal Fayda",
  "Marjinal Fonlama Oranı",
  "Marshmallow Deneyi",
  "Melek Yatırımcı",
  "Menkul Kıymet",
  "Menşe",
  "Merkez Bankası Bağımsızlığı",
  "Mevduat Hesabı",
  "Mevsim etkisinden arındırma",
  "Mikro Ekonomi",
  "Mortgage Bakınız Tutsat",
  "Mutlak üstünlük Absolute Advantage",
  "Nakit Akım Tablosu",
  "Nakit Akışı",
  "Narh",
  "Neoliberalizm",
  "Net Aktif",
  "Net Bugünkü Değer",
  "Niceliksel",
  "Nominal Değer",
  "Nominal döviz kuru",
  "Nominal faiz",
  "Nörofinans",
  "O Ö",
  "OPEC",
  "Odea",
  "Operasyonel Risk",
  "Opsiyon",
  "Opsiyon İşlemi",
  "Orta Gelir Tuzağı",
  "Ortaklık",
  "Ortodoks Ekonomik Yaklaşım",
  "Otomatik Stabilizatörler",
  "PE Oranı",
  "PMI Endeksi",
  "Para",
  "Para  Arzı",
  "Para Arzı Money Supply Money Stock",
  "Para Piyasası Araçları",
  "Para Piyasası Money Market",
  "Para Politikası Monetary Policy",
  "Paradigma",
  "Paranın Dolaşım Hızı Velocity",
  "Parasal Aktarım Mekanizması",
  "Parasal Taban Para Bazı",
  "Parite",
  "Paydaş (Stakeholder) Yaklaşımı",
  "Piyasa",
  "Piyasa Değeri",
  "Piyasa Riski",
  "Portföy",
  "Portföy Yönetimi",
  "Post Otistik Ekonomi",
  "Proje",
  "Rayiç Bedel",
  "Reel Efektif Döviz Kkuru Endeksi REK",
  "Reel Faiz Real Interst Rate",
  "Reel Kazanç",
  "Reel Piyasa",
  "Reeskont Faizi Rediscount Rate",
  "Reeskont Kredisi",
  "Reeskont Politikası Rediscount Policy",
  "Reeskont Rediscount",
  "Repo",
  "Repo ve Ters Repo",
  "Resesyon",
  "Resesyon Recession",
  "Revalüasyon",
  "Rezerv",
  "Rezerv Para",
  "Risk",
  "Risk Toleransı",
  "Risk Yönetimi",
  "Riskten Korunma",
  "RobO",
  "SWOT Analizi",
  "Sabit Kur",
  "Sabit Yatırım Tutarı",
  "Satınalma Gücü Paritesi SAGP ya SGP",
  "Satış kuru",
  "Saç Traşı Haircut",
  "Serbest Nakit Akımı (SNA)",
  "Sermaye",
  "Sermaye  Hasıla Katsayısı",
  "Sermaye Artırımı",
  "Sermaye Piyasası",
  "Sermaye Piyasası Araçları",
  "Sermaye Piyasası Oranları",
  "Sigorta",
  "Sistematik Olmayan Risk",
  "Sistematik Risk",
  "Slumpflasyon",
  "Spekülasyon",
  "Spekülatör",
  "Spot Piyasa",
  "Stagflasyon",
  "Sterilizasyon",
  "Stok Devir Hızı",
  "Stok Değişimi",
  "Stratejik Yatırım",
  "Stres Testi",
  "Structural Reforms",
  "Sukuk",
  "Swap",
  "Swap İşlemi",
  "Sıcak Para Hot Money",
  "Tahkim Konsolidasyon",
  "Tahvil",
  "Takvim etkisinden arındırma",
  "Takvim ve mevsim etkisinden arındırma",
  "Talep",
  "Tasarruf",
  "Tasarruf Hesabı",
  "Tasarruf Çelişkisi",
  "Taylor Kuralı",
  "Tekel",
  "Teknik Analiz",
  "Tekno Yatırım Destek Programı",
  "Tevsi Yatırım",
  "Tezgahüstü Piyasa",
  "Tobin Vergisi Tobin Tax",
  "Toksik Varlıklar",
  "Troika",
  "Tutsat",
  "Tüketici Fiyatları Endeksi (TÜFE)",
  "Tüketim Fonksiyonu",
  "Türev Araçları",
  "Türev Ürünler",
  "Türev Ürünler Derivatives",
  "Türk Lirası Depo Alım İhalesiİşlemleri",
  "Tüyo",
  "U Ü",
  "Uzlaşma Fiyatı",
  "Uzun Pozisyon",
  "Uzun Pozisyon (Long)",
  "Vade",
  "Valör",
  "Varant",
  "Varlık",
  "Varlık Fonu",
  "Varlık Vergisi Servet Vergisi",
  "Varlıklar",
  "Vergi Gayreti",
  "Vergi Kapasitesivergisınırı",
  "Verimlilik",
  "Verimlilik Productivity",
  "Viop",
  "Volatilite",
  "VİOP",
  "Website",
  "Yap  İşlet  Devret modeli",
  "Yapısal Reform",
  "Yastık Altı Birikimi",
  "Yatay Analiz",
  "Yatırım",
  "Yatırım Araçları",
  "Yatırım Fonu",
  "Yatırım Portföyü",
  "Yatırım Yapılabilir Ülke Statüsü",
  "Yatırıma Katkı Tutarı",
  "Yatırımcı",
  "Yeniden Yapılandırma",
  "Yenilenebilir Enerji",
  "Yerleşik kişiler",
  "Yield Verim",
  "Yükümlülükler",
  "Yıllık Bütçe",
  "ZEW Endeksi",
  "Zaman Değeri",
  "Zarar Durdur",
  "Zevki Erteleme Becerisi",
  "Zeyilname",
  "Zorunlu Karşılık",
  "aldığıriskten",
  "dolaylıfinansman",
  "dışsal ya da bağımsız değişken",
  "içsel ya da bağımlıdeğişken",
  "manipülatör denir",
  "ÇED",
  "ÇED (Çevresel Etki Değerlendirmesi)",
  "Çalışma Sermayesi",
  "Çalışma İzni",
  "Çapraz Kur",
  "Çevre (İzin) Lisansı",
  "Çevre Düzeni Planı",
  "Çiftçi Kayıt Sistemi",
  "Çıktı Açığı",
  "Ödemeler Dengesi Balance of Payments",
  "Örümcek Ağı Teoremi",
  "Özel Bütçe",
  "Özelleştirme Privatisation",
  "Özkaynak (Özsermaye)",
  "Özkaynaklar",
  "Özsermaye Kârlılığı",
  "Ülke Riski",
  "Üretici Fiyat Endeksi (ÜFE)",
  "Üretim Fonksiyonu",
  "İ1İ0İ",
  "İ1İ2İ",
  "İ1İ4İ",
  "İ1İ6İ",
  "İ2İ0İ",
  "İ2İ6İ",
  "İ3İ4İ",
  "İ3İ6İ",
  "İ4İ0İ",
  "İ4İ6İ",
  "İ4İ8İ",
  "İ5İ4İ",
  "İ8İ",
  "İAİBİİİGİEİMİ",
  "İAİRİDİEİBİ",
  "İBİ2İBİ",
  "İBİ2İCİ",
  "İBİ2İGİ",
  "İBİBİ",
  "İCİ2İCİ",
  "İCİIİFİ",
  "İCİÇİCİÇİ",
  "İDİAİSİKİ",
  "İDİDİ",
  "İEİ-İTİUİYİSİ",
  "İEİEİ",
  "İFİFİ",
  "İFİOİBİ",
  "İGİEİSİ",
  "İGİGİ",
  "İHİEİSİ",
  "İHİHİ",
  "İIİPİAİ",
  "İIİPİAİRİDİ",
  "İIİİİIİİİ",
  "İKİAİYİSİ",
  "İKİGİFİ",
  "İKİKİ",
  "İKİOİBİİİ",
  "İLİLİ",
  "İMİMİ",
  "İNİNİ",
  "İNİUİTİSİ",
  "İOİÖİOİÖİ",
  "İPİPİ",
  "İRİEİSİ",
  "İRİRİ",
  "İSİSİ",
  "İTİEİKİMİEİRİ",
  "İTİEİYİDİEİBİ",
  "İTİKİDİKİ",
  "İTİOİBİBİ",
  "İTİSİEİ",
  "İTİTİ",
  "İTİÜİBİİİTİAİKİ",
  "İTİÜİİİKİ",
  "İTİİİMİ",
  "İUİÜİUİÜİ",
  "İVİVİ",
  "İYİOİİİKİKİ",
  "İYİYİ",
  "İZİZİ",
  "İfraz",
  "İhracat Reeskont Kredisi",
  "İhtisas Organize Sanayi Bölgesi",
  "İhtiyaç Yönetimi",
  "İkarus Çelişkisi",
  "İmknsız Üçleme Impossible Trinity",
  "İnovasyon",
  "İpotek",
  "İthal İkame",
  "İthal İkamesi",
  "İçeriği paylaşmak ister misiniz",
  "İçeriğinde  bulunan parasal varlıklar",
  "İİİŞİGİEİMİ",
  "İİİŞİKİUİRİ",
  "İşlem Hacmi",
  "İşletme",
  "İşletme Sermayesi",
  "İşsizlik",
  "İşsizlik Histeresisi",
  "İşsizlik Oranı",
  "İşsizlik Sigortası Fonu",
  "İşsizlik Çeşitleri",
  "Şangay İşbirliği Örgütü",
  "Şirket Tahvili"
];