export type FigureType = "economist" | "genius";
export type FigureOrigin = "local" | "foreign";

export interface HistoricFigure {
  id: string;
  name: string;
  type: FigureType;
  origin: FigureOrigin;
  wikiSlug: string; 
  title?: string;
  bio?: string;
  achievements?: string[];
  imageUrl?: string;
  wikiUrl?: string;
}

export const historicFiguresRegistry: HistoricFigure[] = [
  // --- YERLİ / İSLAMİ DEHALAR & EKONOMİSTLER (local) ---
  { id: "reg_l_1", name: "Ali Kuşçu", type: "genius", origin: "local", wikiSlug: "Ali_Kuşçu" },
  { id: "reg_l_2", name: "Biruni", type: "genius", origin: "local", wikiSlug: "Biruni" },
  { id: "reg_l_3", name: "El Cezeri", type: "genius", origin: "local", wikiSlug: "El-Cezeri" },
  { id: "reg_l_4", name: "İbn-i Sina", type: "genius", origin: "local", wikiSlug: "İbn-i_Sina" },
  { id: "reg_l_5", name: "Farabi", type: "genius", origin: "local", wikiSlug: "Farabi" },
  { id: "reg_l_6", name: "Harezmi", type: "genius", origin: "local", wikiSlug: "Harezmi" },
  { id: "reg_l_7", name: "Akşemseddin", type: "genius", origin: "local", wikiSlug: "Akşemseddin" },
  { id: "reg_l_8", name: "Piri Reis", type: "genius", origin: "local", wikiSlug: "Piri_Reis" },
  { id: "reg_l_9", name: "Mimar Sinan", type: "genius", origin: "local", wikiSlug: "Mimar_Sinan" },
  { id: "reg_l_10", name: "İbn-i Haldun", type: "economist", origin: "local", wikiSlug: "İbn-i_Haldun" },
  { id: "reg_l_11", name: "Gazzali", type: "economist", origin: "local", wikiSlug: "Gazzali" },
  { id: "reg_l_12", name: "Ahi Evran", type: "economist", origin: "local", wikiSlug: "Ahi_Evran" },
  { id: "reg_l_13", name: "Cabir bin Hayyan", type: "genius", origin: "local", wikiSlug: "Cabir_bin_Hayyan" },
  { id: "reg_l_14", name: "Takiyüddin", type: "genius", origin: "local", wikiSlug: "Takiyüddin" },
  { id: "reg_l_15", name: "Uluğ Bey", type: "genius", origin: "local", wikiSlug: "Uluğ_Bey" },
  { id: "reg_l_16", name: "Cahit Arf", type: "genius", origin: "local", wikiSlug: "Cahit_Arf" },
  { id: "reg_l_17", name: "Aziz Sancar", type: "genius", origin: "local", wikiSlug: "Aziz_Sancar" },
  { id: "reg_l_18", name: "Oktay Sinanoğlu", type: "genius", origin: "local", wikiSlug: "Oktay_Sinanoğlu" },
  { id: "reg_l_19", name: "Feza Gürsey", type: "genius", origin: "local", wikiSlug: "Feza_Gürsey" },
  { id: "reg_l_20", name: "Behram Kurşunoğlu", type: "genius", origin: "local", wikiSlug: "Behram_Kurşunoğlu" },
  { id: "reg_l_21", name: "Hulusi Behçet", type: "genius", origin: "local", wikiSlug: "Hulusi_Behçet" },
  { id: "reg_l_22", name: "Gazi Yaşargil", type: "genius", origin: "local", wikiSlug: "Gazi_Yaşargil" },
  { id: "reg_l_23", name: "Celâl Şengör", type: "genius", origin: "local", wikiSlug: "Celâl_Şengör" },
  { id: "reg_l_24", name: "İlber Ortaylı", type: "genius", origin: "local", wikiSlug: "İlber_Ortaylı" },
  { id: "reg_l_25", name: "Halil İnalcık", type: "genius", origin: "local", wikiSlug: "Halil_İnalcık" },
  { id: "reg_l_26", name: "Kemal Derviş", type: "economist", origin: "local", wikiSlug: "Kemal_Derviş" },
  { id: "reg_l_27", name: "Özgür Demirtaş", type: "economist", origin: "local", wikiSlug: "Özgür_Demirtaş" },
  { id: "reg_l_28", name: "Daron Acemoğlu", type: "economist", origin: "local", wikiSlug: "Daron_Acemoğlu" },
  { id: "reg_l_29", name: "Refet Gürkaynak", type: "economist", origin: "local", wikiSlug: "Refet_Gürkaynak" },
  { id: "reg_l_30", name: "Mahfi Eğilmez", type: "economist", origin: "local", wikiSlug: "Mahfi_Eğilmez" },
  { id: "reg_l_31", name: "Sabri Ülgener", type: "economist", origin: "local", wikiSlug: "Sabri_Ülgener" },
  { id: "reg_l_32", name: "İdris Küçükömer", type: "economist", origin: "local", wikiSlug: "İdris_Küçükömer" },
  { id: "reg_l_33", name: "Şevket Pamuk", type: "economist", origin: "local", wikiSlug: "Şevket_Pamuk" },
  { id: "reg_l_34", name: "Gülten Kazgan", type: "economist", origin: "local", wikiSlug: "Gülten_Kazgan" },
  { id: "reg_l_35", name: "Hezarfen Ahmed Çelebi", type: "genius", origin: "local", wikiSlug: "Hezarfen_Ahmed_Çelebi" },
  { id: "reg_l_36", name: "Lagari Hasan Çelebi", type: "genius", origin: "local", wikiSlug: "Lagari_Hasan_Çelebi" },
  { id: "reg_l_37", name: "Katip Çelebi", type: "genius", origin: "local", wikiSlug: "Kâtip_Çelebi" },
  { id: "reg_l_38", name: "Evliya Çelebi", type: "genius", origin: "local", wikiSlug: "Evliya_Çelebi" },
  { id: "reg_l_39", name: "Fatih Sultan Mehmet", type: "genius", origin: "local", wikiSlug: "II._Mehmed" },
  { id: "reg_l_40", name: "Ahmet Cevdet Paşa", type: "economist", origin: "local", wikiSlug: "Ahmet_Cevdet_Paşa" },
  { id: "reg_l_41", name: "Ömer Lütfi Barkan", type: "economist", origin: "local", wikiSlug: "Ömer_Lütfi_Barkan" },
  { id: "reg_l_42", name: "Korkut Boratav", type: "economist", origin: "local", wikiSlug: "Korkut_Boratav" },
  { id: "reg_l_43", name: "Dani Rodrik", type: "economist", origin: "local", wikiSlug: "Dani_Rodrik" },
  { id: "reg_l_44", name: "Mete Atatüre", type: "genius", origin: "local", wikiSlug: "Mete_Atatüre" },
  { id: "reg_l_45", name: "Canan Dağdeviren", type: "genius", origin: "local", wikiSlug: "Canan_Dağdeviren" },
  { id: "reg_l_46", name: "Feryal Özel", type: "genius", origin: "local", wikiSlug: "Feryal_Özel" },
  { id: "reg_l_47", name: "Betül Kaçar", type: "genius", origin: "local", wikiSlug: "Betül_Kaçar" },
  { id: "reg_l_48", name: "Şehrazat", type: "genius", origin: "local", wikiSlug: "Şehrazat" },
  { id: "reg_l_49", name: "Selçuk Bayraktar", type: "genius", origin: "local", wikiSlug: "Selçuk_Bayraktar" },
  { id: "reg_l_50", name: "Erol Gelenbe", type: "genius", origin: "local", wikiSlug: "Erol_Gelenbe" },
  { id: "reg_l_51", name: "Ahmet Yesevi", type: "genius", origin: "local", wikiSlug: "Ahmed_Yesevî" },
  { id: "reg_l_52", name: "Ali Erdemir", type: "genius", origin: "local", wikiSlug: "Ali_Erdemir" },
  { id: "reg_l_53", name: "Asuman Baytop", type: "genius", origin: "local", wikiSlug: "Asuman_Baytop" },
  { id: "reg_l_54", name: "Behçet Uz", type: "genius", origin: "local", wikiSlug: "Behçet_Uz" },
  { id: "reg_l_55", name: "Dilhan Eryurt", type: "genius", origin: "local", wikiSlug: "Dilhan_Eryurt" },
  { id: "reg_l_56", name: "Engin Arık", type: "genius", origin: "local", wikiSlug: "Engin_Arık" },
  { id: "reg_l_57", name: "Gökhan Hotamışlıgil", type: "genius", origin: "local", wikiSlug: "Gökhan_Hotamışlıgil" },
  { id: "reg_l_58", name: "Hasan Çelebi", type: "genius", origin: "local", wikiSlug: "Hasan_Çelebi" },
  { id: "reg_l_59", name: "İbrahim Müteferrika", type: "genius", origin: "local", wikiSlug: "İbrahim_Müteferrika" },
  { id: "reg_l_60", name: "Kemal Kafadar", type: "genius", origin: "local", wikiSlug: "Kemal_Kafadar" },
  { id: "reg_l_61", name: "Matrakçı Nasuh", type: "genius", origin: "local", wikiSlug: "Matrakçı_Nasuh" },
  { id: "reg_l_62", name: "Mazhar Osman", type: "genius", origin: "local", wikiSlug: "Mazhar_Osman_Usman" },
  { id: "reg_l_63", name: "Muazzez İlmiye Çığ", type: "genius", origin: "local", wikiSlug: "Muazzez_İlmiye_Çığ" },
  { id: "reg_l_64", name: "Nuri Demirağ", type: "genius", origin: "local", wikiSlug: "Nuri_Demirağ" },
  { id: "reg_l_65", name: "Ömer Hayyam", type: "genius", origin: "local", wikiSlug: "Ömer_Hayyam" },
  { id: "reg_l_66", name: "Ratip Berker", type: "genius", origin: "local", wikiSlug: "Ratip_Berker" },
  { id: "reg_l_67", name: "Safiye Ali", type: "genius", origin: "local", wikiSlug: "Safiye_Ali" },
  { id: "reg_l_68", name: "Salih Zeki", type: "genius", origin: "local", wikiSlug: "Salih_Zeki" },
  { id: "reg_l_69", name: "Sırrı Erinç", type: "genius", origin: "local", wikiSlug: "Sırrı_Erinç" },
  { id: "reg_l_70", name: "Tevfik Sağlam", type: "genius", origin: "local", wikiSlug: "Tevfik_Sağlam" },

  // --- YABANCI DEHALAR & EKONOMİSTLER (foreign) ---
  { id: "reg_f_1", name: "Albert Einstein", type: "genius", origin: "foreign", wikiSlug: "Albert_Einstein" },
  { id: "reg_f_2", name: "Isaac Newton", type: "genius", origin: "foreign", wikiSlug: "Isaac_Newton" },
  { id: "reg_f_3", name: "Nikola Tesla", type: "genius", origin: "foreign", wikiSlug: "Nikola_Tesla" },
  { id: "reg_f_4", name: "Leonardo da Vinci", type: "genius", origin: "foreign", wikiSlug: "Leonardo_da_Vinci" },
  { id: "reg_f_5", name: "Marie Curie", type: "genius", origin: "foreign", wikiSlug: "Marie_Curie" },
  { id: "reg_f_6", name: "Alan Turing", type: "genius", origin: "foreign", wikiSlug: "Alan_Turing" },
  { id: "reg_f_7", name: "Charles Darwin", type: "genius", origin: "foreign", wikiSlug: "Charles_Darwin" },
  { id: "reg_f_8", name: "Galileo Galilei", type: "genius", origin: "foreign", wikiSlug: "Galileo_Galilei" },
  { id: "reg_f_9", name: "Stephen Hawking", type: "genius", origin: "foreign", wikiSlug: "Stephen_Hawking" },
  { id: "reg_f_10", name: "Adam Smith", type: "economist", origin: "foreign", wikiSlug: "Adam_Smith" },
  { id: "reg_f_11", name: "John Maynard Keynes", type: "economist", origin: "foreign", wikiSlug: "John_Maynard_Keynes" },
  { id: "reg_f_12", name: "Milton Friedman", type: "economist", origin: "foreign", wikiSlug: "Milton_Friedman" },
  { id: "reg_f_13", name: "David Ricardo", type: "economist", origin: "foreign", wikiSlug: "David_Ricardo" },
  { id: "reg_f_14", name: "Friedrich Hayek", type: "economist", origin: "foreign", wikiSlug: "Friedrich_Hayek" },
  { id: "reg_f_15", name: "Karl Marx", type: "economist", origin: "foreign", wikiSlug: "Karl_Marx" },
  { id: "reg_f_16", name: "Joseph Schumpeter", type: "economist", origin: "foreign", wikiSlug: "Joseph_Schumpeter" },
  { id: "reg_f_17", name: "Amartya Sen", type: "economist", origin: "foreign", wikiSlug: "Amartya_Sen" },
  { id: "reg_f_18", name: "Thomas Malthus", type: "economist", origin: "foreign", wikiSlug: "Thomas_Robert_Malthus" },
  { id: "reg_f_19", name: "Alfred Marshall", type: "economist", origin: "foreign", wikiSlug: "Alfred_Marshall" },
  { id: "reg_f_20", name: "Max Planck", type: "genius", origin: "foreign", wikiSlug: "Max_Planck" },
  { id: "reg_f_21", name: "Niels Bohr", type: "genius", origin: "foreign", wikiSlug: "Niels_Bohr" },
  { id: "reg_f_22", name: "Richard Feynman", type: "genius", origin: "foreign", wikiSlug: "Richard_Feynman" },
  { id: "reg_f_23", name: "Ada Lovelace", type: "genius", origin: "foreign", wikiSlug: "Ada_Lovelace" },
  { id: "reg_f_24", name: "Grace Hopper", type: "genius", origin: "foreign", wikiSlug: "Grace_Hopper" },
  { id: "reg_f_25", name: "James Clerk Maxwell", type: "genius", origin: "foreign", wikiSlug: "James_Clerk_Maxwell" },
  { id: "reg_f_26", name: "Johannes Kepler", type: "genius", origin: "foreign", wikiSlug: "Johannes_Kepler" },
  { id: "reg_f_27", name: "Nicolaus Copernicus", type: "genius", origin: "foreign", wikiSlug: "Nicolaus_Copernicus" },
  { id: "reg_f_28", name: "Sigmund Freud", type: "genius", origin: "foreign", wikiSlug: "Sigmund_Freud" },
  { id: "reg_f_29", name: "Carl Jung", type: "genius", origin: "foreign", wikiSlug: "Carl_Jung" },
  { id: "reg_f_30", name: "Thomas Edison", type: "genius", origin: "foreign", wikiSlug: "Thomas_Edison" },
  { id: "reg_f_31", name: "Alexander Graham Bell", type: "genius", origin: "foreign", wikiSlug: "Alexander_Graham_Bell" },
  { id: "reg_f_32", name: "Guglielmo Marconi", type: "genius", origin: "foreign", wikiSlug: "Guglielmo_Marconi" },
  { id: "reg_f_33", name: "Steve jobs", type: "genius", origin: "foreign", wikiSlug: "Steve_Jobs" },
  { id: "reg_f_34", name: "Bill Gates", type: "genius", origin: "foreign", wikiSlug: "Bill_Gates" },
  { id: "reg_f_35", name: "Jeff Bezos", type: "genius", origin: "foreign", wikiSlug: "Jeff_Bezos" },
  { id: "reg_f_36", name: "Elon Musk", type: "genius", origin: "foreign", wikiSlug: "Elon_Musk" },
  { id: "reg_f_37", name: "John von Neumann", type: "genius", origin: "foreign", wikiSlug: "John_von_Neumann" },
  { id: "reg_f_38", name: "Claude Shannon", type: "genius", origin: "foreign", wikiSlug: "Claude_Shannon" },
  { id: "reg_f_39", name: "Ludwig von Mises", type: "economist", origin: "foreign", wikiSlug: "Ludwig_von_Mises" },
  { id: "reg_f_40", name: "Paul Samuelson", type: "economist", origin: "foreign", wikiSlug: "Paul_Samuelson" },
  { id: "reg_f_41", name: "Robert Solow", type: "economist", origin: "foreign", wikiSlug: "Robert_Solow" },
  { id: "reg_f_42", name: "Gary Becker", type: "economist", origin: "foreign", wikiSlug: "Gary_Becker" },
  { id: "reg_f_43", name: "Joan Robinson", type: "economist", origin: "foreign", wikiSlug: "Joan_Robinson" },
  { id: "reg_f_44", name: "Thorstein Veblen", type: "economist", origin: "foreign", wikiSlug: "Thorstein_Veblen" },
  { id: "reg_f_45", name: "Elinor Ostrom", type: "economist", origin: "foreign", wikiSlug: "Elinor_Ostrom" },
  { id: "reg_f_46", name: "Janet Yellen", type: "economist", origin: "foreign", wikiSlug: "Janet_Yellen" },
  { id: "reg_f_47", name: "Christine Lagarde", type: "economist", origin: "foreign", wikiSlug: "Christine_Lagarde" },
  { id: "reg_f_48", name: "Thomas Piketty", type: "economist", origin: "foreign", wikiSlug: "Thomas_Piketty" },
  { id: "reg_f_49", name: "Nassim Taleb", type: "economist", origin: "foreign", wikiSlug: "Nassim_Nicholas_Taleb" },
  { id: "reg_f_50", name: "Daniel Kahneman", type: "economist", origin: "foreign", wikiSlug: "Daniel_Kahneman" },
  { id: "reg_f_51", name: "John Dalton", type: "genius", origin: "foreign", wikiSlug: "John_Dalton" },
  { id: "reg_f_52", name: "Dmitri Mendeleev", type: "genius", origin: "foreign", wikiSlug: "Dmitri_Mendeleev" },
  { id: "reg_f_53", name: "Louis Pasteur", type: "genius", origin: "foreign", wikiSlug: "Louis_Pasteur" },
  { id: "reg_f_54", name: "Gregor Mendel", type: "genius", origin: "foreign", wikiSlug: "Gregor_Mendel" },
  { id: "reg_f_55", name: "Enrico Fermi", type: "genius", origin: "foreign", wikiSlug: "Enrico_Fermi" },
  { id: "reg_f_56", name: "Werner Heisenberg", type: "genius", origin: "foreign", wikiSlug: "Werner_Heisenberg" },
  { id: "reg_f_57", name: "Erwin Schrödinger", type: "genius", origin: "foreign", wikiSlug: "Erwin_Schrödinger" },
  { id: "reg_f_58", name: "Linus Pauling", type: "genius", origin: "foreign", wikiSlug: "Linus_Pauling" },
  { id: "reg_f_59", name: "Francis Crick", type: "genius", origin: "foreign", wikiSlug: "Francis_Crick" },
  { id: "reg_f_60", name: "James Watson", type: "genius", origin: "foreign", wikiSlug: "James_Watson" },
  { id: "reg_f_61", name: "Rachel Carson", type: "genius", origin: "foreign", wikiSlug: "Rachel_Carson" },
  { id: "reg_f_62", name: "Rosalind Franklin", type: "genius", origin: "foreign", wikiSlug: "Rosalind_Franklin" },
  { id: "reg_f_63", name: "Barbara McClintock", type: "genius", origin: "foreign", wikiSlug: "Barbara_McClintock" },
  { id: "reg_f_64", name: "Jane Goodall", type: "genius", origin: "foreign", wikiSlug: "Jane_Goodall" },
  { id: "reg_f_65", name: "Richard Dawkins", type: "genius", origin: "foreign", wikiSlug: "Richard_Dawkins" },
  { id: "reg_f_66", name: "Srinivasa Ramanujan", type: "genius", origin: "foreign", wikiSlug: "Srinivasa_Ramanujan" },
  { id: "reg_f_67", name: "Euclid", type: "genius", origin: "foreign", wikiSlug: "Euclid" },
  { id: "reg_f_68", name: "Archimedes", type: "genius", origin: "foreign", wikiSlug: "Archimedes" },
  { id: "reg_f_69", name: "Pythagoras", type: "genius", origin: "foreign", wikiSlug: "Pythagoras" },
  { id: "reg_f_70", name: "Rene Descartes", type: "genius", origin: "foreign", wikiSlug: "René_Descartes" },
];

export const historicFigures: HistoricFigure[] = [
  {
    id: "g_loc_1",
    name: "Ali Kuşçu",
    type: "genius",
    origin: "local",
    title: "Matematik ve Astronomi Dehası",
    bio: "Semerkant'ta doğdu. Uluğ Bey'in rasathanesinde müdürlük yaptı. Ayasofya Medresesi'nde baş müderris oldu.",
    achievements: ["Fethiye adlı eseriyle astronominin temellerini attı.", "Ekvatorun eğiklik derecesini hesapladı."],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Ali_Ku%C5%9F%C3%A7u_Portre.jpg",
    wikiUrl: "https://tr.wikipedia.org/wiki/Ali_Ku%C5%9F%C3%A7u",
    wikiSlug: "Ali_Kuşçu"
  },
  {
      id: "g_for_1",
      name: "Albert Einstein",
      type: "genius",
      origin: "foreign",
      title: "Modern Fiziğin Öncüsü",
      bio: "İzafiyet Teorisi ile Uzay, Zaman ve Kütleçekimi kavramlarını tamamen değiştirdi.",
      achievements: ["E=mc² formülünü geliştirdi.", "Fotoelektrik etkiyi teorize etti."],
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Albert_Einstein_Head_cleaned.jpg/960px-Albert_Einstein_Head_cleaned.jpg",
      wikiUrl: "https://tr.wikipedia.org/wiki/Albert_Einstein",
      wikiSlug: "Albert_Einstein"
  }
];
